# system config
mode: 1
distribute: False
#num_parallel_workers: 1
val_while_train: True

# dataset config
dataset: 'imagenet'
data_dir: 'D:\dataset\imagenet'
shuffle: True
dataset_download: False
batch_size: 8
drop_remainder: True

# Augmentation config
image_resize: 224
scale: [0.08, 1.0]
ratio: [0.75, 1.333]
color_jitter: [0.4, 0.4, 0.4]
hflip: 0.5
vflip: 0.
interpolation: 'bicubic'
auto_augment: True
mixup: 0.8
crop_pct: 0.9    #'crop_pct': .9
re_prob: 0.5

# model config
model: 'coat_tiny'
num_classes: 1000
pretrained: False
ckpt_path: ''
keep_checkpoint_max: 10
ckpt_save_dir: './'
epoch_size: 50
dataset_sink_mode: True
amp_level: 'O2'

# loss config
loss: 'CE'
label_smoothing: 0.1

# lr scheduler config
scheduler: 'warmup_cosine_decay'
min_lr: 0.000001
lr: 0.00005
warmup_epochs: 5
decay_epochs: 30
decay_rate: 0.1

# optimizer config
opt: 'adamw'
filter_bias_and_bn: True
momentum: 0.9
weight_decay: 0.05
loss_scale: 1024
use_nesterov: False
